apiVersion: v2
name: paigham-nats
description: A Helm chart for Paigham - NATS JetStream Management UI
type: application
version: 1.0.3
appVersion: "1.0.2"
kubeVersion: ">=1.23.0"
keywords:
  - nats
  - jetstream
  - messaging
  - management
  - ui
maintainers:
  - name: Paigham
    url: https://github.com/LetsConvert-IO/paigham-nats
home: https://github.com/LetsConvert-IO/paigham-nats
sources:
  - https://github.com/LetsConvert-IO/paigham-nats
